spring:
  datasource:
    url: jdbc:mysql://192.168.2.29:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  liquibase:
    enabled: false
    change-log: classpath:demo-migration.yaml
